---
# This playbook contains common plays for all nodes.

- name: set hostname
  hostname: name={{inventory_hostname}}
  tags: sf

- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400
  tags: sf

- name: install Avahi service
  apt: name=avahi-daemon state=latest
  tags: sf

- name: start Avahi service
  service: enabled=yes state=started name="avahi-daemon"
  tags: sf

- name: install ntp
  apt: name=ntp state=latest
  tags: ntp

- name: start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: install extra packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ common.extras }}"
  tags: sf

- name: update all packages
  apt: upgrade=dist
