---
# This playbook contains common plays for workstation nodes.

- name: install python packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ workstation.python }}"

- name: install jupyter
  pip: name=jupyter executable=pip3

- name: install dev tool packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ workstation.tools }}"

- name: install cuda packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ workstation.cuda }}"

- name: install libs packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ workstation.libs }}"

- name: clone OpenCV repository
  git: repo=http://github.com/opencv/opencv
       dest=/usr/local/src/opencv
       version=b34272f8a2517b98511d6a3fe9103cdb2a292bb1
  register: git_status

- name: create OpenCV build directory
  file: path=/usr/local/src/opencv/build state=directory mode=0755

- name: run cmake
  command: cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
  args:
    chdir: /usr/local/src/opencv/build
  when: git_status|changed

- name: build OpenCV
  command: make -j4
  args:
    chdir: /usr/local/src/opencv/build
  when: git_status|changed

- name: install OpenCV
  command: make install
  args:
    chdir: /usr/local/src/opencv/build
  when: git_status|changed

- name: install Atom deb
  apt: deb={{ atom.deb }}
