---
# file: golang/tasks/main.yml

- name: register the current go version
  command: /{{ golang.dest }}/go/bin/go version
  ignore_errors: yes
  register: golang_version
  changed_when: false
  tags: go

- name: download Go distribution
  get_url: url={{ golang.tarball }} sha256sum={{ golang.sha256 }} dest=/usr/local/src
  when: golang_version|failed or golang_version.stdout != golang.target_version
  tags: go

- name: unarchive Go distribution
  unarchive: src=/usr/local/src/{{ golang.tarball|basename }} dest={{ golang.dest }} copy=no
  when: golang_version|failed or golang_version.stdout != golang.target_version
  tags: go

- name: set path to go tools
  template: src=go-bin.sh.j2 dest=/etc/profile.d/go-bin.sh mode=0644
  tags: go

- name: set go path in home dirs
  copy: src=go-path.sh dest=/etc/profile.d mode=0644
  tags: go
